# Generated by Django 5.0.6 on 2024-06-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
