# Generated by Django 5.0.6 on 2024-06-26 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('type', models.CharField(choices=[('back', 'Back End'), ('front', 'Front End'), ('ios', 'Ios'), ('android', 'Android')], max_length=7)),
                ('created_type', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(related_name='project_contributors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
